// /// Flutter icons AppIcons
// /// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
// /// This font was generated by FlutterIcon.com, which is derived from Fontello.
// ///
// /// To use this font, place it in your fonts/ directory and include the
// /// following in your pubspec.yaml
// ///
// /// flutter:
// ///   fonts:
// ///    - family:  AppIcons
// ///      fonts:
// ///       - asset: fonts/AppIcons.ttf
// ///
// ///
// ///
// import 'package:flutter/widgets.dart';
//
// class AppIcons {
//   AppIcons._();
//
//   static const _kFontFam = 'AppIcons';
//   static const String? _kFontPkg = null;
//
//
//   //static const IconData close = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData vector = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData vector__1_ = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData close_fill1_wght400_grad0_opsz48_1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData search_fill1_wght400_grad0_opsz48_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData call_fill1_wght500_grad0_opsz48_1 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData lock_fill1_wght500_grad0_opsz48_1 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData point_of_sale_fill1_wght400_grad0_opsz48_1 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData lock_fill1_wght400_grad0_opsz48_1 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData inventory_2_fill1_wght400_grad0_opsz48_1 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData house_user = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData home_fill1_wght400_grad0_opsz48_1 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData contract_fill1_wght400_grad0_opsz48_1 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData delete_fill1_wght400_grad0_opsz48_1 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData expand_more_fill0_wght400_grad0_opsz48_1 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData vector__2_ = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
// }
